-- =====================================================================
-- Çetinkaya Elektromekanik — Supabase şeması
-- Supabase panelinde: SQL Editor → New query → bu dosyanın tamamını
-- yapıştırıp "Run". Ardından seed.sql ile örnek içerik yüklenebilir.
-- Tekrar çalıştırılabilir (idempotent).
-- =====================================================================

-- ---------- Tablolar ----------
create table if not exists public.settings (
  key   text primary key,
  value text not null default ''
);

create table if not exists public.categories (
  id   bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique
);

create table if not exists public.posts (
  id           bigint generated by default as identity primary key,
  title        text not null,
  slug         text not null unique,
  excerpt      text not null default '',
  content      text not null default '',
  cover        text not null default '',
  category_id  bigint references public.categories(id) on delete set null,
  status       text not null default 'draft' check (status in ('draft', 'published')),
  featured     integer not null default 0,
  views        integer not null default 0,
  meta_title   text not null default '',
  meta_desc    text not null default '',
  published_at timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
create index if not exists posts_status_idx on public.posts (status, published_at);

create table if not exists public.services (
  id      bigint generated by default as identity primary key,
  title   text not null,
  slug    text not null unique,
  icon    text not null default 'wrench',
  summary text not null default '',
  content text not null default '',
  sort    integer not null default 0,
  active  integer not null default 1
);

create table if not exists public.faqs (
  id       bigint generated by default as identity primary key,
  question text not null,
  answer   text not null,
  sort     integer not null default 0,
  active   integer not null default 1
);

create table if not exists public.product_categories (
  id           bigint generated by default as identity primary key,
  name         text not null,
  slug         text not null unique,
  art          text not null default 'tank',
  summary      text not null default '',
  sort         integer not null default 0,
  photo        text not null default '',
  photo_credit text not null default '',
  photo_source text not null default ''
);

create table if not exists public.products (
  id          bigint generated by default as identity primary key,
  title       text not null,
  slug        text not null unique,
  category_id bigint references public.product_categories(id) on delete set null,
  brand       text not null default '',
  image       text not null default '',
  summary     text not null default '',
  content     text not null default '',
  specs       text not null default '',
  model       text not null default '',
  featured    integer not null default 0,
  active      integer not null default 1,
  sort        integer not null default 0,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index if not exists products_cat_idx on public.products (category_id, active);

create table if not exists public.quotes (
  id           bigint generated by default as identity primary key,
  code         text not null unique,
  type         text not null default 'product',
  name         text not null,
  company      text not null default '',
  phone        text not null,
  email        text not null default '',
  city         text not null default '',
  product_id   bigint references public.products(id) on delete set null,
  product_name text not null default '',
  category     text not null default '',
  quantity     text not null default '',
  message      text not null default '',
  status       text not null default 'new' check (status in ('new', 'contacted', 'quoted', 'won', 'lost')),
  admin_note   text not null default '',
  source       text not null default 'web',
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
create index if not exists quotes_status_idx on public.quotes (status, created_at desc);

create table if not exists public.quote_log (
  id         bigint generated by default as identity primary key,
  quote_id   bigint not null references public.quotes(id) on delete cascade,
  status     text not null,
  note       text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.messages (
  id         bigint generated by default as identity primary key,
  name       text not null,
  email      text not null default '',
  phone      text not null default '',
  subject    text not null default '',
  message    text not null,
  is_read    integer not null default 0,
  created_at timestamptz not null default now()
);

-- Yönetici listesi (Supabase Auth kullanıcıları)
create table if not exists public.admins (
  user_id    uuid primary key references auth.users(id) on delete cascade,
  email      text not null default '',
  created_at timestamptz not null default now()
);

-- ---------- Yardımcı fonksiyonlar ----------
create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.admins where user_id = auth.uid());
$$;

-- İlk oluşturulan kullanıcı otomatik yönetici olur (sonrakileri admins tablosuna elle ekleyin)
create or replace function public.first_user_is_admin()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if not exists (select 1 from public.admins) then
    insert into public.admins (user_id, email) values (new.id, coalesce(new.email, ''));
  end if;
  return new;
end $$;
drop trigger if exists on_auth_user_created_admin on auth.users;
create trigger on_auth_user_created_admin after insert on auth.users
  for each row execute function public.first_user_is_admin();

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at := now(); return new; end $$;
drop trigger if exists posts_touch on public.posts;
create trigger posts_touch before update on public.posts for each row execute function public.touch_updated_at();
drop trigger if exists products_touch on public.products;
create trigger products_touch before update on public.products for each row execute function public.touch_updated_at();
drop trigger if exists quotes_touch on public.quotes;
create trigger quotes_touch before update on public.quotes for each row execute function public.touch_updated_at();

-- Durum değişince teklif geçmişine otomatik kayıt
create or replace function public.log_quote_status()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if tg_op = 'INSERT' then
    insert into public.quote_log (quote_id, status, note)
    values (new.id, new.status, case when new.source = 'web' then 'Web sitesinden teklif talebi.' else 'Kayıt panelden oluşturuldu.' end);
  elsif new.status is distinct from old.status then
    insert into public.quote_log (quote_id, status, note) values (new.id, new.status, '');
  end if;
  return new;
end $$;
drop trigger if exists quotes_log on public.quotes;
create trigger quotes_log after insert or update of status on public.quotes
  for each row execute function public.log_quote_status();

create or replace function public.new_quote_code()
returns text language plpgsql as $$
declare c text;
begin
  loop
    c := 'TK-' || to_char(now(), 'YY') || upper(substr(translate(md5(random()::text), '01', ''), 1, 5));
    exit when not exists (select 1 from public.quotes where code = c);
  end loop;
  return c;
end $$;
alter table public.quotes alter column code set default public.new_quote_code();

-- ---------- Ziyaretçi formları (RPC) ----------
-- Ziyaretçiler tablolara doğrudan yazamaz; sadece bu doğrulayan fonksiyonları çağırabilir.
create or replace function public.submit_quote(payload jsonb)
returns text language plpgsql security definer set search_path = public as $$
declare
  v_name  text := left(trim(coalesce(payload->>'name', '')), 120);
  v_phone text := left(trim(coalesce(payload->>'phone', '')), 40);
  v_email text := left(trim(coalesce(payload->>'email', '')), 160);
  v_type  text := coalesce(payload->>'type', 'product');
  v_slug  text := coalesce(payload->>'product_slug', '');
  v_prod  public.products%rowtype;
  v_cat   text := left(trim(coalesce(payload->>'category', '')), 120);
  v_code  text;
begin
  if coalesce(payload->>'website', '') <> '' then
    return 'TK-OK';  -- honeypot
  end if;
  if length(v_name) < 2 then raise exception 'Adınızı yazın.' using errcode = '22023'; end if;
  if length(regexp_replace(v_phone, '\D', '', 'g')) < 10 then raise exception 'Geçerli bir telefon numarası girin.' using errcode = '22023'; end if;
  if v_email <> '' and v_email !~* '^[^@\s]+@[^@\s]+\.[^@\s]+$' then raise exception 'Geçerli bir e-posta adresi girin.' using errcode = '22023'; end if;
  if v_type not in ('product', 'project', 'install', 'service') then v_type := 'product'; end if;
  -- aynı telefondan 30 dakikada en fazla 5 talep
  if (select count(*) from public.quotes where phone = v_phone and created_at > now() - interval '30 minutes') >= 5 then
    raise exception 'Kısa sürede çok fazla talep oluşturdunuz. Lütfen bizi arayın.' using errcode = '22023';
  end if;
  if v_slug <> '' then
    select p.* into v_prod from public.products p where p.slug = v_slug and p.active = 1;
    if found and v_cat = '' then
      select c.name into v_cat from public.product_categories c where c.id = v_prod.category_id;
    end if;
  end if;
  insert into public.quotes (type, name, company, phone, email, city, product_id, product_name, category, quantity, message, source)
  values (v_type, v_name,
          left(trim(coalesce(payload->>'company', '')), 160), v_phone, v_email,
          left(trim(coalesce(payload->>'city', '')), 60),
          v_prod.id, coalesce(v_prod.title, ''), coalesce(v_cat, ''),
          left(trim(coalesce(payload->>'quantity', '')), 120),
          left(trim(coalesce(payload->>'message', '')), 5000), 'web')
  returning code into v_code;
  return v_code;
end $$;

create or replace function public.submit_message(payload jsonb)
returns boolean language plpgsql security definer set search_path = public as $$
declare
  v_name  text := left(trim(coalesce(payload->>'name', '')), 120);
  v_phone text := left(trim(coalesce(payload->>'phone', '')), 40);
  v_email text := left(trim(coalesce(payload->>'email', '')), 160);
  v_msg   text := left(trim(coalesce(payload->>'message', '')), 5000);
begin
  if coalesce(payload->>'website', '') <> '' then return true; end if;
  if length(v_name) < 2 then raise exception 'Adınızı yazın.' using errcode = '22023'; end if;
  if v_phone = '' and v_email = '' then raise exception 'Size ulaşabilmemiz için telefon veya e-posta girin.' using errcode = '22023'; end if;
  if v_email <> '' and v_email !~* '^[^@\s]+@[^@\s]+\.[^@\s]+$' then raise exception 'Geçerli bir e-posta adresi girin.' using errcode = '22023'; end if;
  if length(v_msg) < 10 then raise exception 'Mesajınız en az 10 karakter olmalı.' using errcode = '22023'; end if;
  if (select count(*) from public.messages
      where created_at > now() - interval '10 minutes'
        and ((v_phone <> '' and phone = v_phone) or (v_email <> '' and email = v_email))) >= 5 then
    raise exception 'Çok fazla mesaj gönderdiniz. Lütfen biraz sonra tekrar deneyin.' using errcode = '22023';
  end if;
  insert into public.messages (name, email, phone, subject, message)
  values (v_name, v_email, v_phone, left(trim(coalesce(payload->>'subject', '')), 160), v_msg);
  return true;
end $$;

revoke all on function public.submit_quote(jsonb) from public;
revoke all on function public.submit_message(jsonb) from public;
grant execute on function public.submit_quote(jsonb) to anon, authenticated;
grant execute on function public.submit_message(jsonb) to anon, authenticated;
grant execute on function public.is_admin() to anon, authenticated;

-- ---------- Satır düzeyi güvenlik (RLS) ----------
alter table public.settings enable row level security;
alter table public.categories enable row level security;
alter table public.posts enable row level security;
alter table public.services enable row level security;
alter table public.faqs enable row level security;
alter table public.product_categories enable row level security;
alter table public.products enable row level security;
alter table public.quotes enable row level security;
alter table public.quote_log enable row level security;
alter table public.messages enable row level security;
alter table public.admins enable row level security;

do $$
declare t text;
begin
  -- Herkesin okuyabildiği içerik tabloları; yazma yalnızca yöneticide
  foreach t in array array['settings', 'categories', 'services', 'faqs', 'product_categories'] loop
    execute format('drop policy if exists "public read" on public.%I', t);
    execute format('create policy "public read" on public.%I for select using (true)', t);
  end loop;
  -- Yöneticiler her şeyi yönetir
  foreach t in array array['settings', 'categories', 'posts', 'services', 'faqs', 'product_categories', 'products', 'quotes', 'quote_log', 'messages'] loop
    execute format('drop policy if exists "admin all" on public.%I', t);
    execute format('create policy "admin all" on public.%I for all to authenticated using (public.is_admin()) with check (public.is_admin())', t);
  end loop;
end $$;

drop policy if exists "public read published" on public.posts;
create policy "public read published" on public.posts for select
  using (status = 'published' and published_at <= now());
drop policy if exists "public read active" on public.products;
create policy "public read active" on public.products for select using (active = 1);
drop policy if exists "admins read admins" on public.admins;
create policy "admins read admins" on public.admins for select to authenticated using (public.is_admin());

-- ---------- Görsel deposu ----------
insert into storage.buckets (id, name, public)
values ('media', 'media', true)
on conflict (id) do update set public = true;

drop policy if exists "media public read" on storage.objects;
create policy "media public read" on storage.objects for select using (bucket_id = 'media');
drop policy if exists "media admin write" on storage.objects;
create policy "media admin write" on storage.objects for insert to authenticated with check (bucket_id = 'media' and public.is_admin());
drop policy if exists "media admin update" on storage.objects;
create policy "media admin update" on storage.objects for update to authenticated using (bucket_id = 'media' and public.is_admin());
drop policy if exists "media admin delete" on storage.objects;
create policy "media admin delete" on storage.objects for delete to authenticated using (bucket_id = 'media' and public.is_admin());
