-- Örnek içerik. schema.sql'den SONRA çalıştırın. Mevcut kayıtların üzerine yazmaz.
-- Oluşturan: php tools/export-seed-sql.php

begin;
insert into public.settings (key, value) values ('site_name', 'Çetinkaya Elektromekanik') on conflict (key) do nothing;
insert into public.settings (key, value) values ('site_tagline', 'Modüler Su Depoları · Pompa ve Hidrofor Sistemleri') on conflict (key) do nothing;
insert into public.settings (key, value) values ('meta_description', 'Kocaeli / İzmit''te Meksis modüler su depoları, Grundfos, Wilo, Standart Pompa ve Sumak pompa ve hidrofor sistemleri satışı. Projeye özel keşif, teklif, montaj ve servis.') on conflict (key) do nothing;
insert into public.settings (key, value) values ('phone', '0262 335 13 20') on conflict (key) do nothing;
insert into public.settings (key, value) values ('phone2', '0533 033 79 04') on conflict (key) do nothing;
insert into public.settings (key, value) values ('whatsapp', '0533 033 79 04') on conflict (key) do nothing;
insert into public.settings (key, value) values ('email', 'info@cetinkayaelektromekanik.com.tr') on conflict (key) do nothing;
insert into public.settings (key, value) values ('address', 'Sanayi Mah. 12. Cad. İzmit Sanayi Sitesi 11. Blok No:1, 41040 İzmit / Kocaeli') on conflict (key) do nothing;
insert into public.settings (key, value) values ('address_short', 'İzmit Sanayi Sitesi, Kocaeli') on conflict (key) do nothing;
insert into public.settings (key, value) values ('hours', 'Pazartesi – Cuma: 08:30 – 18:30
Cumartesi: 08:30 – 14:00
Pazar: Kapalı') on conflict (key) do nothing;
insert into public.settings (key, value) values ('map_embed', 'https://www.google.com/maps?q=%C4%B0zmit+Sanayi+Sitesi+11.+Blok+Kocaeli&output=embed') on conflict (key) do nothing;
insert into public.settings (key, value) values ('map_link', 'https://www.google.com/maps/search/?api=1&query=%C3%87etinkaya+Elektromekanik+%C4%B0zmit') on conflict (key) do nothing;
insert into public.settings (key, value) values ('instagram', '') on conflict (key) do nothing;
insert into public.settings (key, value) values ('facebook', '') on conflict (key) do nothing;
insert into public.settings (key, value) values ('linkedin', '') on conflict (key) do nothing;
insert into public.settings (key, value) values ('youtube', '') on conflict (key) do nothing;
insert into public.settings (key, value) values ('brands', 'Meksis|Modüler su depoları
Grundfos|Pompa ve hidrofor sistemleri
Wilo|Pompa ve hidrofor sistemleri
Standart Pompa|Pompa ve hidrofor sistemleri
Sumak|Pompa sistemleri') on conflict (key) do nothing;
insert into public.settings (key, value) values ('hero_badge', 'Su depolama ve pompa sistemlerinde çözüm ortağınız') on conflict (key) do nothing;
insert into public.settings (key, value) values ('hero_title', 'Suyunuzu güvenle depolayın, doğru basınçla ulaştırın.') on conflict (key) do nothing;
insert into public.settings (key, value) values ('hero_text', 'Meksis modüler su depoları ile Grundfos, Wilo, Standart Pompa ve Sumak pompa ve hidrofor sistemlerini projenize uygun seçiyor, hızlı teklif ve montaj desteğiyle teslim ediyoruz.') on conflict (key) do nothing;
insert into public.settings (key, value) values ('stats', '500+|Mutlu müşteri
1.200+|Tamamlanan sipariş
150+|Ürün çeşidi
20+|Yıllık tecrübe') on conflict (key) do nothing;
insert into public.settings (key, value) values ('stats_title', 'Sahada kanıtlanmış çözümler') on conflict (key) do nothing;
insert into public.settings (key, value) values ('stats_text', 'Konut sitelerinden fabrikalara, otellerden tarım işletmelerine kadar yüzlerce projede depoladığımız ve bastığımız su, bugün sorunsuz akmaya devam ediyor.') on conflict (key) do nothing;
insert into public.settings (key, value) values ('about_title', 'Doğru ürün, doğru kapasite, zamanında teslimat.') on conflict (key) do nothing;
insert into public.settings (key, value) values ('about_text', 'Çetinkaya Elektromekanik, İzmit merkezli olarak modüler su depoları, pompa ve hidrofor sistemlerinin satışını yapan bir firmadır.

Meksis modüler su depoları ile Grundfos, Wilo, Standart Pompa ve Sumak markalarının ürünlerini; konut, site, otel, hastane, fabrika ve tarım projelerinin ihtiyacına göre seçiyor, kapasite hesabından teklife, sevkiyattan montaja kadar sürecin her adımında yanınızda oluyoruz.

Satış sonrası keşif, montaj ve bakım desteğimizle kurduğumuz sistemlerin uzun yıllar sorunsuz çalışmasını hedefliyoruz.') on conflict (key) do nothing;
insert into public.settings (key, value) values ('about_values', 'Orijinal ve garantili ürün
İhtiyaca göre doğru kapasite seçimi
Hızlı teklif ve şeffaf fiyatlandırma
Satış sonrası montaj ve bakım desteği') on conflict (key) do nothing;

insert into public.categories (id, name, slug) overriding system value values (1, 'Rehber', 'rehber') on conflict (id) do nothing;
insert into public.categories (id, name, slug) overriding system value values (2, 'Teknik Bilgi', 'teknik-bilgi') on conflict (id) do nothing;
insert into public.categories (id, name, slug) overriding system value values (3, 'Duyurular', 'duyurular') on conflict (id) do nothing;
select setval(pg_get_serial_sequence('public.categories', 'id'), coalesce((select max(id) from public.categories), 1));

insert into public.product_categories (id, name, slug, art, summary, sort, photo, photo_credit, photo_source) overriding system value values (1, 'Modüler Su Depoları', 'moduler-su-depolari', 'tank', 'Galvaniz, paslanmaz, GRP ve izolasyonlu panel seçenekleriyle her kapasiteye uygun modüler depolar.', 1, '', '', '') on conflict (id) do nothing;
insert into public.product_categories (id, name, slug, art, summary, sort, photo, photo_credit, photo_source) overriding system value values (2, 'Hidrofor Sistemleri', 'hidrofor-sistemleri', 'booster', 'Binalarda sabit ve yeterli su basıncı için tek, çift ve çok pompalı hidrofor setleri.', 2, '', '', '') on conflict (id) do nothing;
insert into public.product_categories (id, name, slug, art, summary, sort, photo, photo_credit, photo_source) overriding system value values (3, 'Santrifüj Pompalar', 'santrifuj-pompalar', 'pump', 'Temiz su transferi, ısıtma-soğutma ve sulama için yatay ve dikey santrifüj pompalar.', 3, '', '', '') on conflict (id) do nothing;
insert into public.product_categories (id, name, slug, art, summary, sort, photo, photo_credit, photo_source) overriding system value values (4, 'Dalgıç Pompalar', 'dalgic-pompalar', 'submersible', 'Kuyu, drenaj ve atık su uygulamaları için dalgıç pompa çözümleri.', 4, '', '', '') on conflict (id) do nothing;
select setval(pg_get_serial_sequence('public.product_categories', 'id'), coalesce((select max(id) from public.product_categories), 1));

insert into public.products (id, title, slug, category_id, brand, image, summary, content, specs, model, featured, active, sort, created_at, updated_at) overriding system value values (1, 'Meksis Galvaniz Modüler Su Deposu', 'meksis-galvaniz-moduler-su-deposu', 1, 'Meksis', '', 'Sıcak daldırma galvaniz panellerden oluşan, ekonomik ve dayanıklı modüler su deposu.', '<p>Modüler su depoları, standart ölçülerdeki panellerin sahada cıvatalı bağlantıyla birleştirilmesiyle kurulur. Bu sayede dar kapılardan ve merdivenlerden kolayca taşınır; bodrum, çatı veya teknik hacimlere istenen ölçüde depo kurulabilir.</p><h3>Öne çıkan özellikler</h3><ul><li>Sıcak daldırma galvaniz kaplı çelik paneller</li><li>Sahada hızlı ve kolay montaj</li><li>İhtiyaca göre genişletilebilir kapasite</li><li>Kullanma ve yangın suyu depolamaya uygun</li></ul>', 'Marka|Meksis
Panel malzemesi|Sıcak daldırma galvaniz çelik
Kapasite|Projeye göre
Kullanım alanı|Kullanma suyu, yangın suyu
Montaj|Cıvatalı panel sistemi', 'tank:galvaniz', 1, 1, 1, '2026-09-27 12:34:33+03', '2026-09-27 12:34:33+03') on conflict (id) do nothing;
insert into public.products (id, title, slug, category_id, brand, image, summary, content, specs, model, featured, active, sort, created_at, updated_at) overriding system value values (2, 'Meksis Paslanmaz Çelik Modüler Su Deposu', 'meksis-paslanmaz-celik-moduler-su-deposu', 1, 'Meksis', '', 'Hijyenik içme suyu depolaması için paslanmaz çelik panelli modüler su deposu.', '<p>Modüler su depoları, standart ölçülerdeki panellerin sahada cıvatalı bağlantıyla birleştirilmesiyle kurulur. Bu sayede dar kapılardan ve merdivenlerden kolayca taşınır; bodrum, çatı veya teknik hacimlere istenen ölçüde depo kurulabilir.</p><h3>Öne çıkan özellikler</h3><ul><li>Paslanmaz çelik paneller ile hijyenik depolama</li><li>Korozyona karşı yüksek dayanım</li><li>Kolay temizlenebilir yüzey</li><li>Uzun kullanım ömrü</li></ul>', 'Marka|Meksis
Panel malzemesi|Paslanmaz çelik
Kapasite|Projeye göre
Kullanım alanı|İçme ve kullanma suyu
Montaj|Cıvatalı panel sistemi', 'tank:paslanmaz', 1, 1, 2, '2026-09-27 12:34:33+03', '2026-09-27 12:34:33+03') on conflict (id) do nothing;
insert into public.products (id, title, slug, category_id, brand, image, summary, content, specs, model, featured, active, sort, created_at, updated_at) overriding system value values (3, 'Meksis GRP (CTP) Modüler Su Deposu', 'meksis-grp-ctp-moduler-su-deposu', 1, 'Meksis', '', 'Cam elyaf takviyeli polyester panellerden hafif ve korozyona dayanıklı modüler depo.', '<p>Modüler su depoları, standart ölçülerdeki panellerin sahada cıvatalı bağlantıyla birleştirilmesiyle kurulur. Bu sayede dar kapılardan ve merdivenlerden kolayca taşınır; bodrum, çatı veya teknik hacimlere istenen ölçüde depo kurulabilir.</p><h3>Öne çıkan özellikler</h3><ul><li>Hafif, korozyona dayanıklı GRP paneller</li><li>Işık geçirmeyen yapı ile yosunlaşmaya karşı koruma</li><li>Düşük bakım ihtiyacı</li></ul>', 'Marka|Meksis
Panel malzemesi|GRP (cam elyaf takviyeli polyester)
Kapasite|Projeye göre
Kullanım alanı|İçme ve kullanma suyu
Montaj|Cıvatalı panel sistemi', 'tank:grp', 0, 1, 3, '2026-09-27 12:34:33+03', '2026-09-27 12:34:33+03') on conflict (id) do nothing;
insert into public.products (id, title, slug, category_id, brand, image, summary, content, specs, model, featured, active, sort, created_at, updated_at) overriding system value values (4, 'Meksis İzolasyonlu (Sandviç Panel) Modüler Su Deposu', 'meksis-izolasyonlu-sandvic-panel-moduler-su-deposu', 1, 'Meksis', '', 'Dış mekân ve soğuk iklimler için ısı yalıtımlı panellere sahip modüler su deposu.', '<p>Modüler su depoları, standart ölçülerdeki panellerin sahada cıvatalı bağlantıyla birleştirilmesiyle kurulur. Bu sayede dar kapılardan ve merdivenlerden kolayca taşınır; bodrum, çatı veya teknik hacimlere istenen ölçüde depo kurulabilir.</p><h3>Öne çıkan özellikler</h3><ul><li>Isı yalıtımlı sandviç panel yapısı</li><li>Donma ve aşırı ısınmaya karşı koruma</li><li>Çatı ve açık alan uygulamalarına uygun</li></ul>', 'Marka|Meksis
Panel yapısı|İzolasyonlu sandviç panel
Kapasite|Projeye göre
Kullanım alanı|Dış mekân, çatı uygulamaları
Montaj|Cıvatalı panel sistemi', 'tank:sandvic', 0, 1, 4, '2026-09-27 12:34:33+03', '2026-09-27 12:34:33+03') on conflict (id) do nothing;
insert into public.products (id, title, slug, category_id, brand, image, summary, content, specs, model, featured, active, sort, created_at, updated_at) overriding system value values (5, 'Grundfos Çok Pompalı Hidrofor Seti', 'grundfos-cok-pompali-hidrofor-seti', 2, 'Grundfos', '', 'Frekans kontrollü, yüksek verimli çok pompalı hidrofor sistemi.', '<p>Çok pompalı hidrofor setleri; apartman, site, otel ve hastane gibi değişken su tüketimi olan binalarda sabit basınç sağlar. Frekans kontrolü sayesinde pompalar ihtiyaç kadar çalışır, enerji tüketimi düşer.</p><h3>Öne çıkan özellikler</h3><ul><li>Frekans konvertörlü sabit basınç kontrolü</li><li>Pompalar arası otomatik sıralı çalışma</li><li>Kuru çalışma ve aşırı akım koruması</li><li>Kompakt, montaja hazır şase</li></ul>', 'Marka|Grundfos
Pompa sayısı|2 – 6 (projeye göre)
Kontrol|Frekans kontrollü, sabit basınç
Kullanım alanı|Konut, site, otel, hastane, endüstri', 'booster:3', 1, 1, 5, '2026-09-27 12:34:33+03', '2026-09-27 12:34:33+03') on conflict (id) do nothing;
insert into public.products (id, title, slug, category_id, brand, image, summary, content, specs, model, featured, active, sort, created_at, updated_at) overriding system value values (6, 'Wilo Çift Pompalı Hidrofor Sistemi', 'wilo-cift-pompali-hidrofor-sistemi', 2, 'Wilo', '', 'Asil-yedek veya paralel çalışma imkânı sunan çift pompalı hidrofor seti.', '<p>Çift pompalı hidrofor sistemleri, bir pompanın arıza veya bakım durumunda diğerinin devreye girmesiyle kesintisiz su sağlar.</p><h3>Öne çıkan özellikler</h3><ul><li>Asil-yedek ve paralel çalışma</li><li>Basınç tanklı veya frekans kontrollü seçenekler</li><li>Sessiz ve verimli çalışma</li></ul>', 'Marka|Wilo
Pompa sayısı|2
Kontrol|Basınç şalterli / frekans kontrollü
Kullanım alanı|Apartman, işyeri, küçük tesis', 'booster:2', 1, 1, 6, '2026-09-27 12:34:33+03', '2026-09-27 12:34:33+03') on conflict (id) do nothing;
insert into public.products (id, title, slug, category_id, brand, image, summary, content, specs, model, featured, active, sort, created_at, updated_at) overriding system value values (7, 'Standart Pompa Kompakt Hidrofor', 'standart-pompa-kompakt-hidrofor', 2, 'Standart Pompa', '', 'Müstakil ev ve küçük işletmeler için tek pompalı, kompakt hidrofor.', '<p>Tek pompalı kompakt hidroforlar; müstakil konut, bahçe ve küçük işletmelerde şebeke basıncının yetersiz olduğu durumlarda pratik bir çözümdür.</p><ul><li>Kompakt, kolay montaj</li><li>Basınç tanklı yapı</li><li>Düşük bakım ihtiyacı</li></ul>', 'Marka|Standart Pompa
Pompa sayısı|1
Kullanım alanı|Müstakil konut, bahçe, küçük işletme', 'booster:1', 0, 1, 7, '2026-09-27 12:34:33+03', '2026-09-27 12:34:33+03') on conflict (id) do nothing;
insert into public.products (id, title, slug, category_id, brand, image, summary, content, specs, model, featured, active, sort, created_at, updated_at) overriding system value values (8, 'Grundfos Dikey Çok Kademeli Pompa', 'grundfos-dikey-cok-kademeli-pompa', 3, 'Grundfos', '', 'Yüksek basınç gerektiren uygulamalar için dikey çok kademeli santrifüj pompa.', '<p>Dikey çok kademeli pompalar; hidrofor setleri, kazan besleme, su arıtma ve endüstriyel proseslerde yüksek basınç ihtiyacını az yer kaplayarak karşılar.</p><ul><li>Az yer kaplayan dikey yapı</li><li>Yüksek verim</li><li>Paslanmaz çelik gövde seçenekleri</li></ul>', 'Marka|Grundfos
Tip|Dikey çok kademeli santrifüj
Kullanım alanı|Basınçlandırma, kazan besleme, endüstri', 'pump:vertical', 1, 1, 8, '2026-09-27 12:34:33+03', '2026-09-27 12:34:33+03') on conflict (id) do nothing;
insert into public.products (id, title, slug, category_id, brand, image, summary, content, specs, model, featured, active, sort, created_at, updated_at) overriding system value values (9, 'Wilo Sirkülasyon Pompası', 'wilo-sirkulasyon-pompasi', 3, 'Wilo', '', 'Isıtma, soğutma ve kullanım sıcak suyu sistemleri için sirkülasyon pompası.', '<p>Sirkülasyon pompaları, kapalı devre ısıtma-soğutma sistemlerinde ve kullanım sıcak suyu hatlarında suyun dolaşımını sağlar.</p><ul><li>Enerji verimli motor seçenekleri</li><li>Sessiz çalışma</li><li>Kolay montaj</li></ul>', 'Marka|Wilo
Tip|Sirkülasyon pompası
Kullanım alanı|Isıtma, soğutma, sıcak su', 'pump:circulator', 0, 1, 9, '2026-09-27 12:34:33+03', '2026-09-27 12:34:33+03') on conflict (id) do nothing;
insert into public.products (id, title, slug, category_id, brand, image, summary, content, specs, model, featured, active, sort, created_at, updated_at) overriding system value values (10, 'Sumak Yatay Santrifüj Pompa', 'sumak-yatay-santrifuj-pompa', 3, 'Sumak', '', 'Temiz su transferi ve sulama için yatay milli santrifüj pompa.', '<p>Yatay santrifüj pompalar; su transferi, sulama ve genel amaçlı basınçlandırma uygulamalarında ekonomik ve güvenilir bir çözüm sunar.</p><ul><li>Sağlam döküm gövde</li><li>Kolay bakım</li><li>Geniş debi aralığı</li></ul>', 'Marka|Sumak
Tip|Yatay santrifüj
Kullanım alanı|Su transferi, sulama, basınçlandırma', 'pump:horizontal', 0, 1, 10, '2026-09-27 12:34:33+03', '2026-09-27 12:34:33+03') on conflict (id) do nothing;
insert into public.products (id, title, slug, category_id, brand, image, summary, content, specs, model, featured, active, sort, created_at, updated_at) overriding system value values (11, 'Standart Pompa Derin Kuyu Dalgıç Pompası', 'standart-pompa-derin-kuyu-dalgic-pompasi', 4, 'Standart Pompa', '', 'Derin kuyulardan su temini için paslanmaz çelik gövdeli dalgıç pompa.', '<p>Derin kuyu dalgıç pompaları; tarımsal sulama, içme suyu ve sanayi tesislerinde kuyudan su çekmek için kullanılır.</p><ul><li>Paslanmaz çelik gövde</li><li>Farklı kuyu çaplarına uygun seçenekler</li><li>Yüksek basma yüksekliği</li></ul>', 'Marka|Standart Pompa
Tip|Derin kuyu dalgıç pompa
Kullanım alanı|Sulama, içme suyu, sanayi', 'sub:deep', 1, 1, 11, '2026-09-27 12:34:33+03', '2026-09-27 12:34:33+03') on conflict (id) do nothing;
insert into public.products (id, title, slug, category_id, brand, image, summary, content, specs, model, featured, active, sort, created_at, updated_at) overriding system value values (12, 'Sumak Drenaj Dalgıç Pompası', 'sumak-drenaj-dalgic-pompasi', 4, 'Sumak', '', 'Bodrum, asansör kuyusu ve şantiyelerde su tahliyesi için drenaj pompası.', '<p>Drenaj dalgıç pompaları; su basan bodrumlar, asansör kuyuları, şantiyeler ve rögarlarda biriken suyun tahliyesi için kullanılır.</p><ul><li>Şamandıralı otomatik çalışma seçeneği</li><li>Taşınabilir, hafif yapı</li><li>Kolay kurulum</li></ul>', 'Marka|Sumak
Tip|Drenaj dalgıç pompa
Kullanım alanı|Bodrum, asansör kuyusu, şantiye', 'sub:drain', 0, 1, 12, '2026-09-27 12:34:33+03', '2026-09-27 12:34:33+03') on conflict (id) do nothing;
select setval(pg_get_serial_sequence('public.products', 'id'), coalesce((select max(id) from public.products), 1));

insert into public.posts (id, title, slug, excerpt, content, cover, category_id, status, featured, meta_title, meta_desc, published_at, created_at, updated_at) overriding system value values (1, 'Su Deposu Kapasitesi Nasıl Hesaplanır?', 'su-deposu-kapasitesi-nasil-hesaplanir', 'Binanız için doğru su deposu hacmini belirlemek; kişi sayısı, günlük tüketim ve kesinti süresine bağlıdır. Adım adım hesaplama rehberi.', '<p>Su deposu seçerken en sık yapılan hata, kapasitenin ihtiyaçtan küçük ya da gereğinden büyük seçilmesidir. Küçük depo kesintilerde yetersiz kalır; çok büyük depo ise suyun uzun süre beklemesine ve gereksiz maliyete yol açar.</p><h2>1. Günlük su ihtiyacını belirleyin</h2><p>Konutlarda kişi başı günlük su tüketimi için genellikle <strong>150–200 litre</strong> arası bir değer esas alınır. Örneğin 20 daireli, daire başına ortalama 4 kişinin yaşadığı bir binada:</p><blockquote>20 daire × 4 kişi × 150 litre = 12.000 litre (12 m³) / gün</blockquote><h2>2. Kaç günlük yedek istediğinize karar verin</h2><p>Bölgenizdeki kesinti sıklığına göre depo genellikle <strong>1–2 günlük</strong> ihtiyaca göre boyutlandırılır. Yukarıdaki örnekte 1,5 günlük yedek için yaklaşık 18 m³ hacim gerekir.</p><h2>3. Yangın suyu ihtiyacını ekleyin</h2><p>Yangın tesisatı olan binalarda yangın suyu için ayrılması gereken hacim, ilgili yönetmelik ve proje hesaplarına göre ayrıca eklenmelidir.</p><h2>4. Yerleşim alanını ölçün</h2><p>Modüler depolar standart panellerle kurulduğu için alanınıza göre farklı en-boy-yükseklik kombinasyonları oluşturulabilir. Kapı ve merdiven ölçüleri kurulumu engellemez; paneller içeride birleştirilir.</p><p>Hesaplamada emin olamadığınız noktalar için bize ulaşın; ücretsiz ön değerlendirme ile size uygun depo hacmini birlikte belirleyelim.</p>', '', 1, 'published', 1, '', '', '2026-09-25 15:34:33+03', '2026-09-27 12:34:33+03', '2026-09-27 12:34:33+03') on conflict (id) do nothing;
insert into public.posts (id, title, slug, excerpt, content, cover, category_id, status, featured, meta_title, meta_desc, published_at, created_at, updated_at) overriding system value values (2, 'Hidrofor Seçerken Dikkat Edilmesi Gereken 6 Nokta', 'hidrofor-secerken-dikkat-edilmesi-gereken-6-nokta', 'Kat sayısı, daire sayısı, pompa sayısı ve kontrol tipi… Binanız için doğru hidroforu seçmenin püf noktaları.', '<p>Hidrofor, şebeke basıncının yetersiz kaldığı binalarda suyu istenen basınçla musluklara ulaştıran sistemdir. Doğru seçim hem konforu hem de enerji maliyetini doğrudan etkiler.</p><h2>1. Gerekli debi</h2><p>Aynı anda kullanılan musluk ve cihaz sayısına göre saatlik su ihtiyacı (m³/saat) belirlenir.</p><h2>2. Gerekli basınç</h2><p>Bina yüksekliği, en üst kattaki musluk için gereken basınç ve boru kayıpları hesaba katılır.</p><h2>3. Pompa sayısı</h2><p>Tek pompalı sistemler küçük yapılar için yeterlidir. Apartman ve sitelerde <strong>çift veya çok pompalı</strong> sistemler, bir pompa arızalandığında suyun kesilmemesini sağlar.</p><h2>4. Kontrol tipi</h2><p><strong>Frekans kontrollü</strong> sistemler pompayı ihtiyaç kadar çalıştırır; basınç sabit kalır ve enerji tüketimi belirgin şekilde azalır.</p><h2>5. Basınç tankı</h2><p>Doğru boyutta genleşme tankı, pompanın sık dur-kalk yapmasını önler ve ömrünü uzatır.</p><h2>6. Marka ve servis desteği</h2><p>Yedek parça bulunabilirliği ve satış sonrası destek, uzun vadede en az ürün kadar önemlidir.</p>', '', 1, 'published', 1, '', '', '2026-09-16 15:34:33+03', '2026-09-27 12:34:33+03', '2026-09-27 12:34:33+03') on conflict (id) do nothing;
insert into public.posts (id, title, slug, excerpt, content, cover, category_id, status, featured, meta_title, meta_desc, published_at, created_at, updated_at) overriding system value values (3, 'Modüler Su Deposu mu, Betonarme Depo mu?', 'moduler-su-deposu-mu-betonarme-depo-mu', 'Modüler su depolarının betonarme depolara göre avantajlarını; kurulum, hijyen, bakım ve maliyet açısından karşılaştırdık.', '<p>Binalarda su depolamak için geleneksel olarak betonarme depolar kullanılır. Ancak son yıllarda <strong>modüler su depoları</strong> birçok avantajıyla öne çıkıyor.</p><h2>Kurulum hızı</h2><p>Betonarme depolar kalıp, beton dökümü ve kür süresi gerektirir. Modüler depolar ise hazır panellerin sahada birleştirilmesiyle kısa sürede kurulur.</p><h2>Hijyen</h2><p>Betonarme depolarda zamanla çatlak, sızıntı ve yosunlaşma görülebilir. Paslanmaz çelik veya GRP panelli modüler depolar hijyenik yüzeyleri sayesinde kolay temizlenir.</p><h2>Taşınabilirlik ve esneklik</h2><p>Paneller dar alanlardan taşınabilir; ihtiyaç arttığında depo genişletilebilir, taşınmak gerektiğinde sökülüp yeniden kurulabilir.</p><h2>Bakım</h2><p>Modüler depolarda bakım ve temizlik için içeri erişim kolaydır; hasarlı bir panel tek başına değiştirilebilir.</p><table><thead><tr><th></th><th>Modüler depo</th><th>Betonarme depo</th></tr></thead><tbody><tr><td>Kurulum</td><td>Hızlı</td><td>Uzun</td></tr><tr><td>Hijyen</td><td>Yüksek</td><td>Zamanla azalır</td></tr><tr><td>Genişletme</td><td>Mümkün</td><td>Zor</td></tr><tr><td>Taşınabilirlik</td><td>Var</td><td>Yok</td></tr></tbody></table>', '', 2, 'published', 0, '', '', '2026-09-07 15:34:33+03', '2026-09-27 12:34:33+03', '2026-09-27 12:34:33+03') on conflict (id) do nothing;
insert into public.posts (id, title, slug, excerpt, content, cover, category_id, status, featured, meta_title, meta_desc, published_at, created_at, updated_at) overriding system value values (4, 'Online Teklif Sistemimiz Yayında', 'online-teklif-sistemimiz-yayinda', 'Artık ihtiyacınız olan ürünler için web sitemiz üzerinden dakikalar içinde teklif talebi oluşturabilirsiniz.', '<p>Müşterilerimize daha hızlı hizmet verebilmek için web sitemizde <strong>online teklif sistemini</strong> devreye aldık.</p><h2>Nasıl çalışır?</h2><ol><li><a href="/urunler">Ürünler</a> sayfasından ihtiyacınız olan ürünü seçin veya doğrudan <a href="/teklif-al">Teklif Al</a> formunu doldurun.</li><li>Talebiniz ekibimize anında ulaşır ve size bir talep numarası verilir.</li><li>Satış ekibimiz sizinle iletişime geçerek ihtiyacınıza uygun teklifi hazırlar.</li></ol>', '', 3, 'published', 0, '', '', '2026-08-29 15:34:33+03', '2026-09-27 12:34:33+03', '2026-09-27 12:34:33+03') on conflict (id) do nothing;
select setval(pg_get_serial_sequence('public.posts', 'id'), coalesce((select max(id) from public.posts), 1));

insert into public.services (id, title, slug, icon, summary, content, sort, active) overriding system value values (1, 'Keşif & Projelendirme', 'kesif-projelendirme', 'ruler', 'Yerinde keşif, su ihtiyacı ve depo/pompa kapasite hesabı ile projenize en uygun sistemin belirlenmesi.', '<p>Doğru ürün seçimi, doğru hesapla başlar. Uzman ekibimiz yerinde keşif yaparak kullanım amacını, kişi/ünite sayısını, bina yüksekliğini ve mevcut tesisatı değerlendirir.</p><h3>Neleri hesaplıyoruz?</h3><ul><li>Günlük su ihtiyacı ve depo hacmi</li><li>Depo yerleşimi ve panel ölçüleri</li><li>Gerekli debi ve basma yüksekliği</li><li>Pompa sayısı ve kontrol tipi</li></ul><p>Keşif sonrası size ürün ve kapasite önerisiyle birlikte detaylı teklif sunuyoruz.</p>', 1, 1) on conflict (id) do nothing;
insert into public.services (id, title, slug, icon, summary, content, sort, active) overriding system value values (2, 'Montaj & Kurulum', 'montaj-kurulum', 'wrench', 'Modüler su deposu montajı, hidrofor ve pompa kurulumu ile devreye alma.', '<p>Satın aldığınız modüler su depoları ile pompa ve hidrofor sistemlerinin montajını deneyimli ekiplerimizle yapıyoruz.</p><ul><li>Modüler depo panel montajı ve sızdırmazlık testi</li><li>Hidrofor ve pompa yerleşimi</li><li>Elektrik bağlantıları ve devreye alma</li><li>Çalışma testleri ve kullanıcı bilgilendirmesi</li></ul>', 2, 1) on conflict (id) do nothing;
insert into public.services (id, title, slug, icon, summary, content, sort, active) overriding system value values (3, 'Bakım & Servis', 'bakim-servis', 'gauge', 'Pompa ve hidrofor sistemleri için periyodik bakım, arıza tespiti ve onarım desteği.', '<p>Satış sonrası desteğimizle sistemlerinizin verimli ve kesintisiz çalışmasını sağlıyoruz.</p><ul><li>Periyodik bakım ve kontrol</li><li>Basınç tankı ve şalter ayarları</li><li>Arıza tespiti ve onarım</li><li>Depo temizliği ve dezenfeksiyon yönlendirmesi</li></ul>', 3, 1) on conflict (id) do nothing;
insert into public.services (id, title, slug, icon, summary, content, sort, active) overriding system value values (4, 'Hızlı Sevkiyat', 'hizli-sevkiyat', 'truck', 'Stoktaki ürünlerde hızlı teslimat, proje ürünlerinde planlı sevkiyat.', '<p>Stokta bulunan pompa ve hidrofor ürünlerini hızlıca teslim ediyor, modüler depo ve proje ürünlerinde üretim ve sevkiyat planını sizinle birlikte yapıyoruz.</p>', 4, 1) on conflict (id) do nothing;
select setval(pg_get_serial_sequence('public.services', 'id'), coalesce((select max(id) from public.services), 1));

insert into public.faqs (id, question, answer, sort, active) overriding system value values (1, 'Teklif almak için hangi bilgiler gerekli?', 'Modüler depo için ihtiyaç duyduğunuz yaklaşık hacim (m³) ve depo kurulacak alanın ölçüleri; pompa ve hidrofor için binadaki kat/daire sayısı veya ihtiyaç duyulan debi ve basınç bilgisi yeterlidir. Emin değilseniz sadece kullanım amacını yazmanız yeterli, ekibimiz sizi arayarak birlikte belirler.', 1, 1) on conflict (id) do nothing;
insert into public.faqs (id, question, answer, sort, active) overriding system value values (2, 'Teklife ne kadar sürede dönüş yapıyorsunuz?', 'Standart ürünlerde genellikle aynı gün, projeye özel taleplerde keşif veya bilgi tamamlandıktan sonra en kısa sürede teklif iletiyoruz.', 2, 1) on conflict (id) do nothing;
insert into public.faqs (id, question, answer, sort, active) overriding system value values (3, 'Modüler su deposu hangi ölçülerde kurulabilir?', 'Modüler depolar standart panellerin birleştirilmesiyle kurulduğu için, alanınıza uygun farklı en-boy-yükseklik kombinasyonlarında ve ihtiyacınız olan hacimde tasarlanabilir.', 3, 1) on conflict (id) do nothing;
insert into public.faqs (id, question, answer, sort, active) overriding system value values (4, 'Hangi markaların ürünlerini satıyorsunuz?', 'Meksis modüler su depoları ile Grundfos, Wilo, Standart Pompa ve Sumak markalarının pompa ve hidrofor ürünlerini satıyoruz.', 4, 1) on conflict (id) do nothing;
insert into public.faqs (id, question, answer, sort, active) overriding system value values (5, 'Montaj ve servis hizmeti veriyor musunuz?', 'Evet. Satışını yaptığımız ürünler için keşif, montaj, devreye alma ve periyodik bakım desteği sunuyoruz.', 5, 1) on conflict (id) do nothing;
select setval(pg_get_serial_sequence('public.faqs', 'id'), coalesce((select max(id) from public.faqs), 1));

commit;
