<?php
/**
 * Generates web/lib/generated.ts for the Next.js site: icons, drawings (2D SVG),
 * the built-in logo and default texts — so they stay identical to the PHP version.
 * Usage: php tools/export-next-data.php
 */
putenv('APP_DB_PATH=' . sys_get_temp_dir() . '/cem-export-' . getmypid() . '.sqlite');
$_SERVER['HTTP_HOST'] = 'localhost';
require __DIR__ . '/../app/bootstrap.php';

$src = file_get_contents(__DIR__ . '/../app/helpers.php');
$body = substr($src, strpos($src, 'function icon('));
preg_match_all("/^\s+'([a-z0-9-]+)'\s*=>\s*'(<[^']*)',?\s*$/m", $body, $m, PREG_SET_ORDER);
$icons = [];
foreach ($m as [, $k, $v]) $icons[$k] = $v;

$n = 0;
$gen = function (string $spec, array $opt = []) use (&$n) {
    $n++;
    $svg = model_svg($spec, 'art', $opt);
    return preg_replace('/(id="|#)m' . $n . '(?=[a-z])/', '$1__ID__', $svg);
};
$models = [];
foreach (array_keys(model_types()) as $spec) $models[$spec] = $gen($spec);
$models[''] = $gen('');
$designer = ['full' => $gen('tank:galvaniz', ['w' => 4, 'l' => 3, 'h' => 2, 'dims' => true]), 'compact' => $gen('tank:galvaniz', ['w' => 4, 'l' => 3, 'h' => 2]), 'blogLead' => $gen('tank:grp', ['w' => 3, 'l' => 2, 'h' => 2])];
$logo = ['dark' => str_replace('lgS', '__ID__', site_logo(false)), 'light' => str_replace('lgS', '__ID__', site_logo(true))];

$j = fn($v) => json_encode($v, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT);
$out = "// Generated by tools/export-next-data.php — do not edit by hand.\n"
    . "export const ICONS: Record<string, string> = " . $j($icons) . ";\n\n"
    . "export const MODEL_SVGS: Record<string, string> = " . $j($models) . ";\n\n"
    . "export const DESIGNER_SVGS = " . $j($designer) . ";\n\n"
    . "export const LOGO_SVGS = " . $j($logo) . ";\n\n"
    . "export const TEXT_DEFAULTS: Record<string, string> = " . $j(text_defaults()) . ";\n\n"
    . "export const MODEL_TYPES: Record<string, string> = " . $j(model_types()) . ";\n";
@mkdir(__DIR__ . '/../web/lib', 0775, true);
file_put_contents(__DIR__ . '/../web/lib/generated.ts', $out);
echo count($icons) . " icons, " . count($models) . " models\n";
